const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
const source=ts.transpileModule(fs.readFileSync(require.resolve('../src/location/permissions.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;
function setup(permission, result=permission, fail=false){let stored=null,requests=0;const exports={};const storage={getItem:async()=>stored,setItem:async(_,value)=>{stored=value;}};vm.runInNewContext(source,{exports,require:name=> name.includes('async-storage')?storage:{getForegroundPermissionsAsync:async()=>permission,requestForegroundPermissionsAsync:async()=>{requests++;if(fail)throw Error('unavailable');return result;}}});return {api:exports,requests:()=>requests,stored:()=>stored};}
test('existing installation gets one prompt, concurrent calls do not duplicate it',async()=>{const s=setup({granted:false,canAskAgain:true},{granted:true,canAskAgain:true});await Promise.all([s.api.requestMapLocationAccess(),s.api.requestMapLocationAccess()]);await s.api.requestMapLocationAccess();assert.equal(s.requests(),1);});
test('denial is remembered, manual retry remains possible',async()=>{const s=setup({granted:false,canAskAgain:true});await s.api.requestMapLocationAccess();await s.api.requestMapLocationAccess();assert.equal(s.requests(),1);await s.api.requestMapLocationAccess(true);assert.equal(s.requests(),2);});
test('already granted or permanently denied permissions do not trigger another OS request',async()=>{for(const granted of [true,false]){const s=setup({granted,canAskAgain:false});await s.api.requestMapLocationAccess();assert.equal(s.requests(),0);assert.equal(s.stored(),'handled');}});
test('native errors remain retryable on a later launch',async()=>{const s=setup({granted:false,canAskAgain:true},null,true);await assert.rejects(s.api.requestMapLocationAccess(),/unavailable/);assert.equal(s.stored(),null);});
